public class SimapQueueable {

    // public class FetchPublicationsByCantonsJob implements Queueable, Database.AllowsCallouts {
    //     public void execute(QueueableContext context) {
    //         SimapService.fetchNewPublicationsByCantons();
    //     }
    // }
    
    // public class FetchPublicationsByFederalEntitiesJob implements Queueable, Database.AllowsCallouts {
    //     public void execute(QueueableContext context) {
    //         SimapService.fetchNewPublicationsByFederalEntities();
    //     }
    // }

}